/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Leslie BAMOU
 */
public class adapFil2 extends javax.swing.JFrame {

    /**
     * Creates new form AdaptativeFilteringClass
     */
    public adapFil2() {
        initComponents();
       
    }
    
    public javax.swing.JPanel putit()
    {
            javax.swing.JPanel p = new javax.swing.JPanel ();
            p.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        p.setPreferredSize(new java.awt.Dimension(1292, 630));
        p.setLayout(null);
        
           p.add(AdapFilterChoicePanel);
        AdapFilterChoicePanel.setBounds(10, 280, 530, 260);

        imageAdapFilterPanel.setLayout(new java.awt.GridLayout());
        imageAdapFilterScrollPane.setViewportView(imageAdapFilterPanel);

        
        
        imageAdapFilterScrollPane.setBounds(595, 67, 660, 540);

        mainSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        p.add(mainSeparator);
        mainSeparator.setBounds(560, 20, 14, 590);

        logoAdapLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoAdapLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointCloudProcessing.jpg"))); // NOI18N
        logoAdapLabel.setText("jLabel1");
        p.add(logoAdapLabel);
        logoAdapLabel.setBounds(0, 0, 1260, 650);
        return p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        AdapFilterChoicePanel = new javax.swing.JPanel();
        filterLinearChoiceLabel = new javax.swing.JLabel();
        adapFilterFactorLabel = new javax.swing.JLabel();
        adapFilterCombo = new javax.swing.JComboBox();
        errorMainDisplayScrollPane = new javax.swing.JScrollPane();
        adapFilterDisplayTextArea = new javax.swing.JTextArea();
        okAdapFilterLabel = new javax.swing.JLabel();
        okAdapFilterButton = new javax.swing.JButton();
        adapFilterFactorCombo = new javax.swing.JComboBox();
        logoAdapFilterLabel = new javax.swing.JLabel();
        imageAdapFilterScrollPane = new javax.swing.JScrollPane();
        imageAdapFilterPanel = new javax.swing.JPanel();
        mainSeparator = new javax.swing.JSeparator();
        logoAdapLabel = new javax.swing.JLabel();

        

        AdapFilterChoicePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        filterLinearChoiceLabel.setText("Types of filters:");

        adapFilterFactorLabel.setText("Factor:");

        adapFilterCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LEE filter", "Alternated LEE filter", "MAP filter", "Gamma filter", "Frost filter" }));
        adapFilterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adapFilterComboimageFormatComboActionPerformed(evt);
            }
        });

        adapFilterDisplayTextArea.setBackground(new java.awt.Color(226, 226, 108));
        adapFilterDisplayTextArea.setColumns(20);
        adapFilterDisplayTextArea.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        adapFilterDisplayTextArea.setForeground(new java.awt.Color(51, 153, 0));
        adapFilterDisplayTextArea.setLineWrap(true);
        adapFilterDisplayTextArea.setRows(5);
        adapFilterDisplayTextArea.setText("... Enter the characteristics for the            filtering process ...");
        adapFilterDisplayTextArea.setToolTipText("");
        errorMainDisplayScrollPane.setViewportView(adapFilterDisplayTextArea);

        okAdapFilterLabel.setText("Confirm:");

        okAdapFilterButton.setText("OK");

        adapFilterFactorCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2" }));
        adapFilterFactorCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adapFilterFactorComboActionPerformed(evt);
            }
        });

        logoAdapFilterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoAdapFilterLabel.setText("jLabel1");

        javax.swing.GroupLayout AdapFilterChoicePanelLayout = new javax.swing.GroupLayout(AdapFilterChoicePanel);
        AdapFilterChoicePanel.setLayout(AdapFilterChoicePanelLayout);
        AdapFilterChoicePanelLayout.setHorizontalGroup(
            AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdapFilterChoicePanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterLinearChoiceLabel)
                    .addComponent(adapFilterFactorLabel))
                .addGap(18, 18, 18)
                .addGroup(AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adapFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adapFilterFactorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(errorMainDisplayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(AdapFilterChoicePanelLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(logoAdapFilterLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdapFilterChoicePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okAdapFilterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okAdapFilterButton)
                .addGap(75, 75, 75))
        );
        AdapFilterChoicePanelLayout.setVerticalGroup(
            AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdapFilterChoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoAdapFilterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdapFilterChoicePanelLayout.createSequentialGroup()
                        .addGroup(AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adapFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filterLinearChoiceLabel))
                        .addGap(18, 18, 18)
                        .addGroup(AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adapFilterFactorLabel)
                            .addComponent(adapFilterFactorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(errorMainDisplayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okAdapFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okAdapFilterButton))
                .addGap(43, 43, 43))
        );

    
     

    }// </editor-fold>

    private void adapFilterFactorComboActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void adapFilterComboimageFormatComboActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel AdapFilterChoicePanel;
    public javax.swing.JComboBox adapFilterCombo;
    private javax.swing.JTextArea adapFilterDisplayTextArea;
    private javax.swing.JComboBox adapFilterFactorCombo;
    private javax.swing.JLabel adapFilterFactorLabel;
    private javax.swing.JScrollPane errorMainDisplayScrollPane;
    private javax.swing.JScrollPane errorMainDisplayScrollPane1;
    private javax.swing.JTextArea errorMainDisplayTextArea4;
    private javax.swing.JLabel filterLinearChoiceLabel;
    private javax.swing.JPanel imageAdapFilterPanel;
    private javax.swing.JScrollPane imageAdapFilterScrollPane;
    private javax.swing.JComboBox imageFormatCombo4;
    private javax.swing.JLabel imageFormatLabel4;
    private javax.swing.JScrollPane imageMainBandScrollPane;
    private javax.swing.JPanel inMainBandPanel;
    private javax.swing.JComboBox inputModeChoiceCombo4;
    private javax.swing.JLabel inputModeChoiceLabel4;
    private javax.swing.JLabel logoAdapFilterLabel;
    private javax.swing.JLabel logoAdapLabel;
    private javax.swing.JLabel logoMainImageLabel;
    private javax.swing.JLabel mainChoiceOkButtonLabel4;
    private javax.swing.JPanel mainChoicePanel4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JSeparator mainSeparator;
    private javax.swing.JLabel numBandLabel4;
    private javax.swing.JTextField numBandTextF4;
    private javax.swing.JLabel numColumnLabel4;
    private javax.swing.JTextField numColumnTextF4;
    private javax.swing.JLabel numLineLabel4;
    private javax.swing.JTextField numLineTextF4;
    private javax.swing.JButton okAdapFilterButton;
    private javax.swing.JLabel okAdapFilterLabel;
    private javax.swing.JButton okMainButton4;
    private javax.swing.JButton resetMainButton4;
    private javax.swing.JLabel resetMainChoiceButtonLabel4;
    // End of variables declaration
}
