/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Leslie BAMOU
 */
public class AdaptativeFilteringClass extends javax.swing.JPanel {

    /**
     * Creates new form AdaptativeFilteringClass
     */
    public AdaptativeFilteringClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageAdapFilterScrollPane = new javax.swing.JScrollPane();
        imageAdapFilterPanel = new javax.swing.JPanel();
        AdapFilterChoicePanel = new javax.swing.JPanel();
        filterAdapChoiceLabel = new javax.swing.JLabel();
        adapFilterFactorLabel = new javax.swing.JLabel();
        adapFilterCombo = new javax.swing.JComboBox();
        errorMainDisplayScrollPane = new javax.swing.JScrollPane();
        adapFilterDisplayTextArea = new javax.swing.JTextArea();
        okAdapFilterLabel = new javax.swing.JLabel();
        okAdapFilterButton = new javax.swing.JButton();
        adapFilterFactorCombo = new javax.swing.JComboBox();
        filterAdapBorFillLabl = new javax.swing.JLabel();
        filterAdapBorderFillCombo = new javax.swing.JComboBox();
        mainAdapSeparator = new javax.swing.JSeparator();
        logoAdapLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(1226, 528));
        setLayout(null);

        imageAdapFilterPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout imageAdapFilterPanelLayout = new javax.swing.GroupLayout(imageAdapFilterPanel);
        imageAdapFilterPanel.setLayout(imageAdapFilterPanelLayout);
        imageAdapFilterPanelLayout.setHorizontalGroup(
            imageAdapFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        imageAdapFilterPanelLayout.setVerticalGroup(
            imageAdapFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        imageAdapFilterScrollPane.setViewportView(imageAdapFilterPanel);

        add(imageAdapFilterScrollPane);
        imageAdapFilterScrollPane.setBounds(580, 130, 620, 290);

        AdapFilterChoicePanel.setBackground(new java.awt.Color(255, 255, 255));
        AdapFilterChoicePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AdapFilterChoicePanel.setOpaque(false);

        filterAdapChoiceLabel.setText("Types of filters:");

        adapFilterFactorLabel.setText("Factor:");

        adapFilterCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LEE filter", "Alternated LEE filter", "MAP filter", "Gamma filter", "Frost filter" }));
        adapFilterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adapFilterComboimageFormatComboActionPerformed(evt);
            }
        });

        errorMainDisplayScrollPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        adapFilterDisplayTextArea.setColumns(20);
        adapFilterDisplayTextArea.setEditable(false);
        adapFilterDisplayTextArea.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        adapFilterDisplayTextArea.setForeground(new java.awt.Color(51, 153, 0));
        adapFilterDisplayTextArea.setLineWrap(true);
        adapFilterDisplayTextArea.setRows(5);
        adapFilterDisplayTextArea.setText("... Enter the characteristics for the            filtering process ...");
        adapFilterDisplayTextArea.setToolTipText("");
        errorMainDisplayScrollPane.setViewportView(adapFilterDisplayTextArea);

        okAdapFilterLabel.setText("Confirm:");

        okAdapFilterButton.setText("OK");
        okAdapFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okAdapFilterButtonActionPerformed(evt);
            }
        });

        adapFilterFactorCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2" }));
        adapFilterFactorCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adapFilterFactorComboActionPerformed(evt);
            }
        });

        filterAdapBorFillLabl.setText("Border filling method:");

        filterAdapBorderFillCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Zeros method", "Simple symmetry", "Circular symmetry" }));
        filterAdapBorderFillCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterAdapBorderFillComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdapFilterChoicePanelLayout = new javax.swing.GroupLayout(AdapFilterChoicePanel);
        AdapFilterChoicePanel.setLayout(AdapFilterChoicePanelLayout);
        AdapFilterChoicePanelLayout.setHorizontalGroup(
            AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdapFilterChoicePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdapFilterChoicePanelLayout.createSequentialGroup()
                        .addComponent(filterAdapBorFillLabl)
                        .addGap(18, 18, 18)
                        .addComponent(filterAdapBorderFillCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdapFilterChoicePanelLayout.createSequentialGroup()
                        .addGroup(AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filterAdapChoiceLabel)
                            .addComponent(adapFilterFactorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adapFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adapFilterFactorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(errorMainDisplayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdapFilterChoicePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okAdapFilterLabel)
                .addGap(41, 41, 41)
                .addComponent(okAdapFilterButton)
                .addGap(85, 85, 85))
        );
        AdapFilterChoicePanelLayout.setVerticalGroup(
            AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdapFilterChoicePanelLayout.createSequentialGroup()
                .addGroup(AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdapFilterChoicePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filterAdapBorFillLabl)
                            .addComponent(filterAdapBorderFillCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filterAdapChoiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adapFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adapFilterFactorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adapFilterFactorCombo))
                        .addGap(67, 67, 67))
                    .addGroup(AdapFilterChoicePanelLayout.createSequentialGroup()
                        .addComponent(errorMainDisplayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(AdapFilterChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okAdapFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okAdapFilterButton))
                .addGap(51, 51, 51))
        );

        add(AdapFilterChoicePanel);
        AdapFilterChoicePanel.setBounds(40, 170, 470, 220);

        mainAdapSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(mainAdapSeparator);
        mainAdapSeparator.setBounds(560, 20, 14, 470);

        logoAdapLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoAdapLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointCloudProcessing.jpg"))); // NOI18N
        logoAdapLabel.setText("jLabel1");
        add(logoAdapLabel);
        logoAdapLabel.setBounds(0, 0, 1230, 640);
    }// </editor-fold>//GEN-END:initComponents

    private void adapFilterFactorComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adapFilterFactorComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adapFilterFactorComboActionPerformed

    private void adapFilterComboimageFormatComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adapFilterComboimageFormatComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adapFilterComboimageFormatComboActionPerformed

    private void okAdapFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okAdapFilterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okAdapFilterButtonActionPerformed

    private void filterAdapBorderFillComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterAdapBorderFillComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterAdapBorderFillComboActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdapFilterChoicePanel;
    private javax.swing.JComboBox adapFilterCombo;
    private javax.swing.JTextArea adapFilterDisplayTextArea;
    private javax.swing.JComboBox adapFilterFactorCombo;
    private javax.swing.JLabel adapFilterFactorLabel;
    private javax.swing.JScrollPane errorMainDisplayScrollPane;
    private javax.swing.JLabel filterAdapBorFillLabl;
    private javax.swing.JComboBox filterAdapBorderFillCombo;
    private javax.swing.JLabel filterAdapChoiceLabel;
    private javax.swing.JPanel imageAdapFilterPanel;
    private javax.swing.JScrollPane imageAdapFilterScrollPane;
    private javax.swing.JLabel logoAdapLabel;
    private javax.swing.JSeparator mainAdapSeparator;
    private javax.swing.JButton okAdapFilterButton;
    private javax.swing.JLabel okAdapFilterLabel;
    // End of variables declaration//GEN-END:variables
}
