/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Leslie BAMOU
 */
public class MorphologyClass extends javax.swing.JPanel {

    /**
     * Creates new form MorphologyClass
     */
    public MorphologyClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        binaryChoicePanel = new javax.swing.JPanel();
        binarizeButton = new javax.swing.JButton();
        binarizationBrocessLabel = new javax.swing.JLabel();
        tresholdDefinitionLabel = new javax.swing.JLabel();
        tresholdFromLabel = new javax.swing.JLabel();
        tresholdToLabel = new javax.swing.JLabel();
        tresholdFromTextF = new javax.swing.JTextField();
        tresholdToTextF = new javax.swing.JTextField();
        errorMainMorphDisplayScrollPane = new javax.swing.JScrollPane();
        binaryDisplayTextArea = new javax.swing.JTextArea();
        mainMorphSeparator = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        imageAnalysisScrollPane = new javax.swing.JScrollPane();
        imageAnalysisPanel = new javax.swing.JPanel();
        analysisChoicePanel = new javax.swing.JPanel();
        analyzeCombo = new javax.swing.JComboBox();
        analyzeLabel = new javax.swing.JLabel();
        orderLabel = new javax.swing.JLabel();
        orderCombo = new javax.swing.JTextField();
        okAnalyzeButton = new javax.swing.JButton();
        logoAnalyzeLabel = new javax.swing.JLabel();
        analyzeOkLabel = new javax.swing.JLabel();
        morphBorderFillCombo = new javax.swing.JComboBox();
        morphBorFillLabl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(1220, 528));
        setLayout(null);

        binaryChoicePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        binaryChoicePanel.setOpaque(false);

        binarizeButton.setBackground(new java.awt.Color(153, 153, 153));
        binarizeButton.setText("Binarize");
        binarizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binarizeButtonActionPerformed(evt);
            }
        });

        binarizationBrocessLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        binarizationBrocessLabel.setText("Binarization process:");

        tresholdDefinitionLabel.setText("Treshold definition:");

        tresholdFromLabel.setText("From:");

        tresholdToLabel.setText("to");

        tresholdFromTextF.setColumns(5);
        tresholdFromTextF.setText("(int)");

        tresholdToTextF.setColumns(5);
        tresholdToTextF.setText("(int)");
        tresholdToTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresholdToTextFActionPerformed(evt);
            }
        });

        errorMainMorphDisplayScrollPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        errorMainMorphDisplayScrollPane.setOpaque(false);

        binaryDisplayTextArea.setColumns(10);
        binaryDisplayTextArea.setEditable(false);
        binaryDisplayTextArea.setFont(new java.awt.Font("Mongolian Baiti", 1, 14)); // NOI18N
        binaryDisplayTextArea.setForeground(new java.awt.Color(51, 153, 0));
        binaryDisplayTextArea.setLineWrap(true);
        binaryDisplayTextArea.setRows(5);
        binaryDisplayTextArea.setText("... Enter the characteristics for the            filtering process ...");
        binaryDisplayTextArea.setToolTipText("");
        binaryDisplayTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        errorMainMorphDisplayScrollPane.setViewportView(binaryDisplayTextArea);

        javax.swing.GroupLayout binaryChoicePanelLayout = new javax.swing.GroupLayout(binaryChoicePanel);
        binaryChoicePanel.setLayout(binaryChoicePanelLayout);
        binaryChoicePanelLayout.setHorizontalGroup(
            binaryChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(binaryChoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(binaryChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(binarizationBrocessLabel)
                    .addComponent(tresholdDefinitionLabel)
                    .addGroup(binaryChoicePanelLayout.createSequentialGroup()
                        .addGroup(binaryChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(binaryChoicePanelLayout.createSequentialGroup()
                                .addComponent(tresholdFromLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tresholdFromTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tresholdToLabel))
                            .addComponent(binarizeButton))
                        .addGap(18, 18, 18)
                        .addComponent(tresholdToTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(errorMainMorphDisplayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        binaryChoicePanelLayout.setVerticalGroup(
            binaryChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(binaryChoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(binaryChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorMainMorphDisplayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(binaryChoicePanelLayout.createSequentialGroup()
                        .addComponent(binarizationBrocessLabel)
                        .addGap(18, 18, 18)
                        .addComponent(tresholdDefinitionLabel)
                        .addGap(18, 18, 18)
                        .addGroup(binaryChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tresholdFromLabel)
                            .addComponent(tresholdFromTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tresholdToLabel)
                            .addComponent(tresholdToTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(binarizeButton)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        add(binaryChoicePanel);
        binaryChoicePanel.setBounds(30, 60, 430, 170);

        mainMorphSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(mainMorphSeparator);
        mainMorphSeparator.setBounds(510, 30, 10, 510);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/processing00 - Copy.png"))); // NOI18N
        jLabel1.setText("Binarized image:");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel1);
        jLabel1.setBounds(550, 120, 560, 80);

        imageAnalysisPanel.setBackground(new java.awt.Color(255, 255, 255));
        imageAnalysisPanel.setLayout(new java.awt.GridLayout(1, 0));
        imageAnalysisScrollPane.setViewportView(imageAnalysisPanel);

        add(imageAnalysisScrollPane);
        imageAnalysisScrollPane.setBounds(550, 200, 560, 270);

        analysisChoicePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        analysisChoicePanel.setOpaque(false);

        analyzeCombo.setBackground(new java.awt.Color(153, 153, 153));
        analyzeCombo.setForeground(new java.awt.Color(0, 51, 51));
        analyzeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Erosion", "Dilation", "Opening", "Closure", "White top Hat", "Black Top Hat", "squelettization" }));

        analyzeLabel.setText("Analysis techniques:");

        orderLabel.setText("Order:");

        orderCombo.setColumns(5);
        orderCombo.setText("1");
        orderCombo.setToolTipText("");
        orderCombo.setSelectionColor(new java.awt.Color(204, 204, 204));
        orderCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderComboActionPerformed(evt);
            }
        });

        okAnalyzeButton.setBackground(new java.awt.Color(204, 0, 204));
        okAnalyzeButton.setText("Analyze");
        okAnalyzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okAnalyzeButtonActionPerformed(evt);
            }
        });

        logoAnalyzeLabel.setForeground(new java.awt.Color(102, 102, 102));
        logoAnalyzeLabel.setText(" ------------------ Input: Analysis process characteristic -----------------------------------------");

        analyzeOkLabel.setText("confirm:");

        morphBorderFillCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Zeros method", "Simple symmetry", "Circular symmetry" }));

        morphBorFillLabl.setText("Border filling method:");

        javax.swing.GroupLayout analysisChoicePanelLayout = new javax.swing.GroupLayout(analysisChoicePanel);
        analysisChoicePanel.setLayout(analysisChoicePanelLayout);
        analysisChoicePanelLayout.setHorizontalGroup(
            analysisChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, analysisChoicePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(analyzeOkLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okAnalyzeButton)
                .addGap(29, 29, 29))
            .addGroup(analysisChoicePanelLayout.createSequentialGroup()
                .addComponent(logoAnalyzeLabel)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(analysisChoicePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(analysisChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(analyzeLabel)
                    .addComponent(orderLabel)
                    .addComponent(morphBorFillLabl))
                .addGap(18, 18, 18)
                .addGroup(analysisChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(morphBorderFillCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(analyzeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        analysisChoicePanelLayout.setVerticalGroup(
            analysisChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analysisChoicePanelLayout.createSequentialGroup()
                .addComponent(logoAnalyzeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(analysisChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(analysisChoicePanelLayout.createSequentialGroup()
                        .addGroup(analysisChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(analyzeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(analyzeLabel))
                        .addGap(18, 18, 18)
                        .addComponent(morphBorFillLabl))
                    .addComponent(morphBorderFillCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(analysisChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(analysisChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okAnalyzeButton)
                    .addComponent(analyzeOkLabel))
                .addContainerGap())
        );

        add(analysisChoicePanel);
        analysisChoicePanel.setBounds(30, 280, 430, 220);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointCloudProcessing.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1230, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void tresholdToTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresholdToTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tresholdToTextFActionPerformed

    private void orderComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderComboActionPerformed

    private void okAnalyzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okAnalyzeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okAnalyzeButtonActionPerformed

    private void binarizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binarizeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_binarizeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel analysisChoicePanel;
    private javax.swing.JComboBox analyzeCombo;
    private javax.swing.JLabel analyzeLabel;
    private javax.swing.JLabel analyzeOkLabel;
    private javax.swing.JLabel binarizationBrocessLabel;
    private javax.swing.JButton binarizeButton;
    private javax.swing.JPanel binaryChoicePanel;
    private javax.swing.JTextArea binaryDisplayTextArea;
    private javax.swing.JScrollPane errorMainMorphDisplayScrollPane;
    private javax.swing.JPanel imageAnalysisPanel;
    private javax.swing.JScrollPane imageAnalysisScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logoAnalyzeLabel;
    private javax.swing.JSeparator mainMorphSeparator;
    private javax.swing.JLabel morphBorFillLabl;
    private javax.swing.JComboBox morphBorderFillCombo;
    private javax.swing.JButton okAnalyzeButton;
    private javax.swing.JTextField orderCombo;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JLabel tresholdDefinitionLabel;
    private javax.swing.JLabel tresholdFromLabel;
    private javax.swing.JTextField tresholdFromTextF;
    private javax.swing.JLabel tresholdToLabel;
    private javax.swing.JTextField tresholdToTextF;
    // End of variables declaration//GEN-END:variables
}
