/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Leslie BAMOU
 */
public class SquelettizeClass extends javax.swing.JPanel {

    /**
     * Creates new form SquelettizeClass
     */
    public SquelettizeClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        binaryChoicePanel = new javax.swing.JPanel();
        binarizeButton = new javax.swing.JButton();
        binarizationBrocessLabel = new javax.swing.JLabel();
        tresholdDefinitionLabel = new javax.swing.JLabel();
        tresholdFromLabel = new javax.swing.JLabel();
        tresholdToLabel = new javax.swing.JLabel();
        tresholdFromTextF = new javax.swing.JTextField();
        tresholdToTextF = new javax.swing.JTextField();
        errorMainDisplayScrollPane = new javax.swing.JScrollPane();
        binaryDisplayTextArea = new javax.swing.JTextArea();
        mainSeparator = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1226, 528));

        binaryChoicePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        binaryChoicePanel.setOpaque(false);

        binarizeButton.setText("Binarize");

        binarizationBrocessLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        binarizationBrocessLabel.setText("Binarization process:");

        tresholdDefinitionLabel.setText("Treshold definition:");

        tresholdFromLabel.setText("From:");

        tresholdToLabel.setText("to");

        tresholdFromTextF.setText("(int)");

        tresholdToTextF.setText("(int)");
        tresholdToTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresholdToTextFActionPerformed(evt);
            }
        });

        binaryDisplayTextArea.setBackground(new java.awt.Color(226, 226, 108));
        binaryDisplayTextArea.setColumns(20);
        binaryDisplayTextArea.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        binaryDisplayTextArea.setForeground(new java.awt.Color(51, 153, 0));
        binaryDisplayTextArea.setLineWrap(true);
        binaryDisplayTextArea.setRows(5);
        binaryDisplayTextArea.setText("... Enter the characteristics for the            filtering process ...");
        binaryDisplayTextArea.setToolTipText("");
        binaryDisplayTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        errorMainDisplayScrollPane.setViewportView(binaryDisplayTextArea);

        javax.swing.GroupLayout binaryChoicePanelLayout = new javax.swing.GroupLayout(binaryChoicePanel);
        binaryChoicePanel.setLayout(binaryChoicePanelLayout);
        binaryChoicePanelLayout.setHorizontalGroup(
            binaryChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(binaryChoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(binaryChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(binarizationBrocessLabel)
                    .addComponent(tresholdDefinitionLabel)
                    .addGroup(binaryChoicePanelLayout.createSequentialGroup()
                        .addGroup(binaryChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(binaryChoicePanelLayout.createSequentialGroup()
                                .addComponent(tresholdFromLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tresholdFromTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tresholdToLabel))
                            .addComponent(binarizeButton))
                        .addGap(18, 18, 18)
                        .addComponent(tresholdToTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addComponent(errorMainDisplayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        binaryChoicePanelLayout.setVerticalGroup(
            binaryChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(binaryChoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(binaryChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorMainDisplayScrollPane)
                    .addGroup(binaryChoicePanelLayout.createSequentialGroup()
                        .addComponent(binarizationBrocessLabel)
                        .addGap(18, 18, 18)
                        .addComponent(tresholdDefinitionLabel)
                        .addGap(18, 18, 18)
                        .addGroup(binaryChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tresholdFromLabel)
                            .addComponent(tresholdFromTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tresholdToLabel)
                            .addComponent(tresholdToTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(binarizeButton)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );

        mainSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointCloudProcessing.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(binaryChoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(mainSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(binaryChoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tresholdToTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresholdToTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tresholdToTextFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel binarizationBrocessLabel;
    private javax.swing.JButton binarizeButton;
    private javax.swing.JPanel binaryChoicePanel;
    private javax.swing.JTextArea binaryDisplayTextArea;
    private javax.swing.JScrollPane errorMainDisplayScrollPane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator mainSeparator;
    private javax.swing.JLabel tresholdDefinitionLabel;
    private javax.swing.JLabel tresholdFromLabel;
    private javax.swing.JTextField tresholdFromTextF;
    private javax.swing.JLabel tresholdToLabel;
    private javax.swing.JTextField tresholdToTextF;
    // End of variables declaration//GEN-END:variables
}
